Add reusable workflows
pipedrive-actions/github-actions-workflows pull request #1
Opened 2024-09-23 12:07 UTC by maximlishchenko

Took the implementations of reusable publishing workflows from gha-setup and modified them to either
- checkout gha-setup using GHA_SETUP_ACCESS_TOKEN
- use actions stored directly in github-actions-workflows

Modified all runners to use ubuntu-latest GitHub-hosted runner

Have not tested anything yet

2024-09-24 09:34 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +      NPM_TOKEN:
Public packages doesn't use dependencies from private registry so we can remove it

2024-09-24 09:34 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +      PD_GHA_BOT_APPLICATION_PRIVATE_KEY_PEM:
Normally this credential is used to access internal repos when installing dependecies, so in this case we don't need it

2024-09-24 09:34 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +          GHA_ACCESS_TOKEN: ${{ steps.get-workflow-token.outputs.token}}
Check if we can left this arguments empty or with empty string

2024-09-24 09:34 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +      - name: Set Packages Access
Remove this logic because it will always public

2024-09-24 09:34 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +      NPM_GRANT_ACCESS_TOKEN:
We can remove this token

2024-09-24 10:15 UTC, maximlishchenko commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +      PD_GHA_BOT_APPLICATION_PRIVATE_KEY_PEM:
If we delete this secret, will the get-workflow-token step work? I see on the action's github page that private-key is a required input.

2024-09-24 10:50 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-package-publish.yml
> +      PD_GHA_BOT_APPLICATION_PRIVATE_KEY_PEM:
We can also delete the get-workflow-token step and his depedents. We can use the secrets.GITHUB_TOKEN in this scenario

2024-10-07 13:27 UTC, Moser-ss commented on .github/workflows/reusable_cicd-npm-publish.yml
> +    uses: pipedrive-actions/github-actions-workflows/.github/workflows/reusable_cicd-npm-package-checks.yml@add-reusable-workflows
update the reference to master in all the changes in this file

2024-10-07 13:31 UTC, Moser-ss requested changes
Just update the reference of the reusable workflows

2024-10-07 13:49 UTC, Moser-ss approved these changes

2024-10-08 06:59 UTC, merged